#!/usr/bin/env node
/**
 * cdcstack caps — enforce the budgets declared in rules/RULES.md.
 *
 * The rules file is the configuration. There is no second place to look, so the
 * numbers cannot drift from the prose that explains them.
 *
 * Two properties this check must have, because it is the check that makes the
 * other rules real:
 *
 *   1. It reports EVERY violation in one run. A check that stops at the first
 *      problem turns N violations into N runs.
 *   2. It fails closed. A budget line it cannot parse is a failure, not a
 *      skipped rule with a default — and it prints what it actually counted, so
 *      a run that inspected nothing is visible rather than green.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const RULES_PATH = 'rules/RULES.md';
const CODE_EXTENSIONS = new Set([
  '.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx', '.rs', '.go', '.py', '.rb',
  '.java', '.kt', '.swift', '.c', '.h', '.cc', '.cpp', '.hpp', '.cs', '.php',
]);
const DEAD_STATUSES = new Set(['superseded', 'shelved', 'withdrawn', 'tombstoned', 'archived']);
// Review artifacts and the overlay directories are not design documents. Counting
// them makes the doc cap meaningless — ibex has 78 reviews against 56 documents.
const NON_DOC_DIRS = new Set(['reviews', 'current', 'foundation']);
// Vendored third-party source cannot be refactored, so holding it to the project's
// line cap only inflates the baseline and hides real growth underneath it.
const VENDORED = /(^|\/)(vendor|vendored|vendored-generated|third_party|third-party|external|node_modules)\//;
const GENERATED_MARKER = /@generated|do not edit|generated by/i;

const problems = [];
const counted = [];

function fail(code, message, detail) {
  problems.push({ code, message, detail });
}

/** Parse one number out of the rules file, or fail closed. */
function budget(text, code, pattern, label) {
  const match = text.match(pattern);
  if (!match) {
    fail(code, `${RULES_PATH} does not declare a parseable "${label}" budget.`,
      `caps reads its numbers from the rules file. Restore the line or this rule is unenforced.`);
    return null;
  }
  return Number(match[1].replace(/,/g, ''));
}

function gitFiles(root) {
  const result = spawnSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (result.status !== 0) throw new Error('git ls-files failed — caps must run inside a git repository');
  return result.stdout.split('\0').filter(Boolean);
}

export function runCaps(root = process.cwd()) {
  problems.length = 0;
  counted.length = 0;

  const rulesAbs = resolve(root, RULES_PATH);
  if (!existsSync(rulesAbs)) {
    fail('rules:missing', `${RULES_PATH} does not exist.`,
      'Every other budget is declared there. Without it caps has nothing to enforce and must not pass.');
    return { problems, counted };
  }
  const rules = readFileSync(rulesAbs, 'utf8');

  // ---- the rules file's own word budget -----------------------------------
  const maxWords = budget(rules, 'budget:words', /This file:\s*([\d,]+)\s*words/i, 'rules file words');
  const words = rules.split(/\s+/).filter(Boolean).length;
  counted.push(`${RULES_PATH}: ${words} words`);
  if (maxWords !== null && words > maxWords) {
    fail('cap:words', `${RULES_PATH} is ${words} words, over its declared cap of ${maxWords}.`,
      'Something in it becomes a check, or stops being a rule. That trade is the point.');
  }

  // ---- blocking checks ----------------------------------------------------
  const maxChecks = budget(rules, 'budget:checks', /([\d,]+)\s*blocking checks/i, 'blocking checks');
  const checksHeading = rules.match(/##[^\n]*checks\s*\n+([^\n]+)/i);
  if (!checksHeading) {
    fail('checks:undeclared', `${RULES_PATH} has no section naming the blocking checks.`,
      'caps counts the backticked names under that heading. Without it the cap is unenforced.');
  } else {
    const names = [...checksHeading[1].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
    counted.push(`blocking checks: ${names.length} (${names.join(', ') || 'none named'})`);
    if (maxChecks !== null && names.length > maxChecks) {
      fail('cap:checks', `${names.length} blocking checks declared, over the cap of ${maxChecks}.`,
        `Adding one requires deleting one, in the same change. Declared: ${names.join(', ')}`);
    }
  }

  // ---- the product-latency row must be filled in --------------------------
  if (/\|\s*\*?\*?<[^>]*product latency[^>]*>/i.test(rules) || /required — you must name one/i.test(rules)) {
    fail('cap:product-latency', 'The product-latency budget is still the template placeholder.',
      'Name the latency your users actually feel, and give it a number. There is no default for this row.');
  } else {
    counted.push('product-latency row: filled');
  }

  // ---- the overlays: working set and kernel --------------------------------
  // The corpus is memory and costs nothing while it binds nothing. The overlays
  // are what an agent actually reads to orient (foundation -> current -> refs),
  // so they are what carries a cost and what gets capped. Removing a link is the
  // whole archive operation; the document stays exactly where it was.
  const files = gitFiles(root);
  const corpus = files.filter((f) => f.startsWith('llp/') && f.endsWith('.md') &&
    !f.split('/').slice(1, -1).some((seg) => NON_DOC_DIRS.has(seg))).length;

  for (const [dir, code, pattern, label, note] of [
    ['current', 'cap:current', /([\d,]+)\s*(?:documents|docs)? ?in (?:the )?working set/i, 'working set',
      'Finish or archive one before starting another. Removing the link is the archive.'],
    ['foundation', 'cap:foundation', /([\d,]+)\s*(?:documents|docs)? ?in (?:the )?foundation/i, 'foundation',
      'The kernel is the smallest set the design could be recreated from. A large one means the admission test is not being applied.'],
  ]) {
    const max = budget(rules, code.replace('cap:', 'budget:'), pattern, label);
    const odir = resolve(root, 'llp', dir);
    const entries = existsSync(odir)
      ? readdirSync(odir).filter((n) => !n.startsWith('.')).length
      : 0;
    // An empty overlay over a real corpus is an unused overlay, not a small one:
    // the cap would pass while measuring nothing. Say so rather than reporting green.
    const vacuous = entries === 0 && corpus > 0;
    counted.push(`${label}: ${entries}${max !== null ? ` of ${max}` : ''}` +
      (vacuous ? ` — OVERLAY UNUSED, ${corpus} docs tracked and none linked; this cap measures nothing` : ''));
    if (max !== null && entries > max) {
      fail(code, `${entries} documents in ${label}, over the cap of ${max}.`, note);
    }
  }

  // ---- source file size ---------------------------------------------------
  const maxLines = budget(rules, 'budget:lines', /([\d,]+)\s*lines per source file/i, 'lines per source file');
  // A retrofit into an existing codebase declares how many files are already
  // over the cap. The count may not grow; driving it down is deliberate work.
  // Without this an adoption is red on day one, and a check that is red on day
  // one gets switched off in a week.
  const lineBaseline = /lines per source file[^\n]*baseline\s+([\d,]+)/i.exec(rules);
  const allowedOversize = lineBaseline ? Number(lineBaseline[1].replace(/,/g, '')) : 0;
  const sources = files.filter((f) => CODE_EXTENSIONS.has(extname(f)) && !VENDORED.test(f));
  const vendored = files.filter((f) => CODE_EXTENSIONS.has(extname(f)) && VENDORED.test(f)).length;
  let scanned = 0;
  let generated = 0;
  const oversize = [];
  for (const f of sources) {
    const abs = resolve(root, f);
    if (!existsSync(abs) || !statSync(abs).isFile()) continue;
    const text = readFileSync(abs, 'utf8');
    if (GENERATED_MARKER.test(text.slice(0, 512))) { generated += 1; continue; }
    scanned += 1;
    const lines = text.split('\n').length;
    if (maxLines !== null && lines > maxLines) oversize.push({ f, lines });
  }
  counted.push(`source files: ${scanned} scanned, ${generated} skipped as generated` +
    (vendored ? `, ${vendored} skipped as vendored` : ''));
  // Every file skipped is only implausible once there are enough of them; a
  // two-file repository may legitimately be all generated.
  const ALL_SKIPPED_THRESHOLD = 5;
  if (sources.length >= ALL_SKIPPED_THRESHOLD && scanned === 0) {
    fail('sources:all-skipped', `All ${sources.length} source files were skipped as generated.`,
      'That is almost certainly a bad marker pattern rather than a repository of generated code.');
  }
  if (allowedOversize > 0) counted.push(`oversize files: ${oversize.length} of ${allowedOversize} allowed by baseline`);
  if (oversize.length > allowedOversize) {
    // Name only the overflow, sorted largest first — listing all 132 files of a
    // retrofit buries the one that broke the baseline.
    for (const { f, lines } of oversize.sort((a, b) => b.lines - a.lines).slice(0, oversize.length - allowedOversize)) {
      fail('cap:lines', `${f} is ${lines} lines, over the cap of ${maxLines}.`,
        allowedOversize > 0 ? `Baseline allows ${allowedOversize} oversize files; there are ${oversize.length}.` : null);
    }
  } else if (allowedOversize > 0 && oversize.length < allowedOversize) {
    counted.push(`  baseline can be tightened to ${oversize.length}`);
  }

  return { problems, counted };
}

function main() {
  const root = spawnSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).stdout.trim() || process.cwd();
  const { problems: found, counted: inspected } = runCaps(root);

  console.log('caps — budgets declared in ' + RULES_PATH + '\n');
  for (const line of inspected) console.log('  ' + line);
  console.log('');

  if (found.length === 0) {
    console.log(`All budgets within cap. ${inspected.length} categories inspected.`);
    return 0;
  }
  for (const p of found) {
    console.log(`  ${p.code}`);
    console.log(`    ${p.message}`);
    if (p.detail) console.log(`    ${p.detail}`);
    console.log('');
  }
  console.log(`${found.length} ${found.length === 1 ? 'violation' : 'violations'}.`);
  return 1;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main());
